name: flutter_study
description: flutter study

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.4
  apple_sign_in: ^0.1.0
  cloud_firestore: ^0.13.2+1
  modal_progress_hud: ^0.1.3
  webview_flutter: ^0.3.19+7
  firebase_crashlytics: ^0.1.3
  charts_flutter: ^0.8.1
  page_indicator: ^0.3.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^3.1.3
  speech_to_text: ^0.8.0
  http: ^0.12.0+4

  #permission_handler: ^3.2.0
  camera: ^0.5.7+4
  #path_provider: ^1.6.1
  #path: ^1.6.4
  image_picker: ^0.6.3+4
  firebase_messaging: ^6.0.9
  provider: ^4.0.4
  flutter_ble: ^0.5.3
  flutter_clean_calendar: ^1.0.1
  calendar_strip: ^1.0.6

  flutter_calendar_carousel: ^1.4.11
  table_calendar: ^2.2.2
  google_fonts: ^0.3.9
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/a/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Bold.ttf