name: flutter_study
description: flutter study

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  modal_progress_hud: ^0.1.3
  webview_flutter: ^0.3.19+7
  firebase_crashlytics: ^0.1.3
  charts_flutter: ^0.8.1
  rflutter_alert: ^1.0.2
  page_indicator: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - images/a/